import type { UIBlock } from "./ui";

// ── Model tier types ──────────────────────────────────────────────────

export interface ModelEntry {
  id: string;
  name: string;
  description: string;
}

export interface BackendModels {
  name: string;
  models: ModelEntry[];
}

export interface ModelsListResult {
  backends: BackendModels[];
}

export interface ModelPreference {
  backend: string;
  model: string;
}

// Attachments come in two shapes that share ``kind``/``name``/``media_type``
// but differ in where the bytes live:
//
// 1. **Inline** — the payload is carried on the message itself via ``data``
//    (base64 for images/documents) or ``text`` (decoded UTF-8 for text).
//    This is how user uploads from the chat input arrive: the frontend
//    base64-encodes the file, the server validates, and the blob rides
//    through storage as part of the message row.
//
// 2. **Workspace reference** — ``workspace_skill`` + ``workspace_path``
//    name a file already on disk under the user's skill workspace. No
//    bytes are carried on the message; the frontend calls
//    ``skills.workspace.download`` when the user clicks download. This is
//    how assistant attachments (PDFs/images generated by a tool script)
//    arrive — we keep the binary out of the conversation row so chat
//    history stays small.
//
// Both modes can appear on either user or assistant messages, though in
// practice user messages are always inline and assistant messages are
// almost always references.
export interface FileAttachmentBase {
  /** Discriminator.
   *  - ``image`` / ``document`` / ``text``: AI-readable kinds,
   *    forwarded to the model as multimodal content blocks.
   *  - ``file``: opaque catch-all for anything else the user wants
   *    to upload (zips, videos, docx, binaries, …). The bytes
   *    round-trip so the download chip renders, but the AI only
   *    sees a text stub naming the file + size + mime type. */
  kind: "image" | "document" | "text" | "file";
  name?: string;
  media_type: string;
  /** Inline base64 payload (images/documents/files). */
  data?: string;
  /** Inline UTF-8 payload (text attachments). */
  text?: string;
  /** Workspace reference: which skill's workspace the file lives in. */
  workspace_skill?: string;
  /** Workspace reference: file path within that workspace. */
  workspace_path?: string;
  /** Workspace reference: conversation id whose per-conv workspace
   *  holds the file. Empty for legacy attachments persisted before
   *  per-conversation workspaces — those resolve via the legacy
   *  per-(user, skill) path on the backend. */
  workspace_conv?: string;
  /** Entity ID in the workspace_files registry. When set, the file
   *  can be resolved via the registry instead of path-based lookup. */
  workspace_file_id?: string;
  /** Decoded byte size of the file. Filled in at upload time for
   *  reference-mode attachments (``POST /api/chat/upload`` returns
   *  it) and for inline attachments (``_parse_frame_attachments``
   *  sets it after base64 decode). Zero when not known — callers
   *  can fall back to computing from ``data.length`` for inline
   *  attachments. */
  size?: number;
}

export type FileAttachment = FileAttachmentBase;

export function isReferenceAttachment(
  att: FileAttachment,
): att is FileAttachmentBase & { workspace_skill: string; workspace_path: string } {
  return !!att.workspace_path && !!att.workspace_skill;
}

export interface ConversationSummary {
  conversation_id: string;
  title: string;
  preview: string;
  updated_at: string;
  message_count: number;
  shared: boolean;
  member_count?: number;
  members?: ConversationMember[];
  visibility?: "public" | "invite";
  is_member?: boolean;
  is_invited?: boolean;
  /** Optional grouping hint set by services that own conversation
   *  creation. ``"agent"`` for an Agent's personal conv, ``"war_room"``
   *  for goal war rooms, empty string otherwise. */
  kind?: string;
  /** When ``kind === "agent"``, the owning Agent's id so the SPA can
   *  link the sidebar entry back to ``/agents/<id>``. */
  agent_id?: string;
  /** Number of messages newer than this user's
   *  ``last_read_mention_index`` cursor that @-mention them. Drives
   *  the dot/count badge on the sidebar entry. Reset via the
   *  ``chat.conversation.mark_mentions_read`` RPC when the user
   *  focuses the conversation. */
  unread_mentions_count?: number;
}

export interface ConversationMember {
  user_id: string;
  display_name: string;
  role?: "owner" | "member";
}

export interface ConversationDetail {
  conversation_id: string;
  title: string;
  /** Turn-grouped history. Each turn is one user→assistant exchange
   *  with intermediate rounds + final answer. Replaces the old
   *  ``messages`` field. */
  turns: ChatTurn[];
  ui_blocks: UIBlock[];
  updated_at: string;
  shared: boolean;
  members?: ConversationMember[];
  invites?: { user_id: string; display_name: string }[];
  owner_id?: string;
  model_preference?: ModelPreference;
}

export interface ToolUsageEntry {
  tool_name: string;
  is_error: boolean;
  arguments?: Record<string, unknown>;
  result?: string;
  /** The assistant's reasoning preamble from the round that dispatched
   *  this tool — e.g. "Let me check the skill workspace first..." that
   *  the AI said alongside the tool_use block. Rendered in the
   *  "tools used" panel so the reasoning stays visible across the turn,
   *  not just during the brief streaming window before the next round. */
  reasoning?: string;
}

export interface ChatResponse {
  response: string;
  conversation_id: string;
  ui_blocks: UIBlock[];
  tool_usage?: ToolUsageEntry[];
  attachments?: FileAttachment[];
  /** Per-round breakdown of intermediate AI reasoning + tool calls.
   *  The frontend uses this as the authoritative committed shape for
   *  the just-finished turn, replacing whatever live state the
   *  streaming buffer accumulated during the RPC. */
  rounds?: ChatRound[];
  /** True when the turn was interrupted mid-flight by the user via
   *  ``chat.message.cancel``. Partial state (completed rounds, any
   *  attachments produced before the stop) is preserved in the
   *  response; the frontend renders a subtle stop indicator. */
  interrupted?: boolean;
  /** The model ID that handled this turn (echoed from the backend). */
  model?: string;
  /** Aggregate token + cost totals for the whole turn (sum over every
   *  round including the final end_turn round). The chat UI renders
   *  this once per turn bubble. */
  turn_usage?: TurnUsage | null;
}

// ── Token/cost usage shapes ──────────────────────────────────────────

export interface RoundUsage {
  input_tokens: number;
  output_tokens: number;
  cache_creation_tokens: number;
  cache_read_tokens: number;
  cost_usd: number;
  /** AI backend (provider) name that handled this round — ``anthropic``,
   *  ``openai``, ``gemini``, etc. Empty when usage was recorded before
   *  this field shipped. */
  backend?: string;
  /** Model ID the backend reported for this round's response. */
  model?: string;
}

export interface TurnUsage extends RoundUsage {
  /** How many AI rounds contributed to this total (tool rounds plus the
   *  final end_turn round). */
  rounds: number;
}

// ── Turn-grouped chat history ────────────────────────────────────────
//
// A "turn" is one user → assistant exchange. The user side is a single
// message; the assistant side is one or more agentic ``rounds`` (each
// round being a chunk of reasoning text followed by some tool calls)
// plus a ``final`` answer carrying the user-visible reply text and any
// downloadable attachments.
//
// This shape is what ``chat.history.load.result`` returns and what
// ``chat.message.send.result`` includes alongside the legacy fields. The
// frontend renders one ``TurnBubble`` per ``ChatTurn``.
export interface ChatRoundTool {
  tool_call_id: string;
  tool_name: string;
  arguments?: Record<string, unknown>;
  result?: string;
  is_error?: boolean;
  /** "running" only used during live streaming; persisted history
   *  entries are always "done". */
  status?: "running" | "done";
}

export interface ChatRound {
  reasoning: string;
  tools: ChatRoundTool[];
  /** Per-round token + cost numbers. Present on live turns and on any
   *  historical round that was recorded after the usage-tracking feature
   *  shipped. Older rounds won't have it. */
  usage?: RoundUsage;
}

export interface ChatTurnUserMessage {
  content: string;
  attachments: FileAttachment[];
  author_id?: string;
  author_name?: string;
}

export interface ChatTurn {
  user_message: ChatTurnUserMessage;
  rounds: ChatRound[];
  final_content: string;
  final_attachments: FileAttachment[];
  final_author_id?: string;
  final_author_name?: string;
  /** True if the turn never produced a final assistant message — the
   *  agentic loop hit max_tool_rounds or the AI errored. Interrupted
   *  turns use the ``interrupted`` flag instead; this one is for
   *  unintentional incompletion. */
  incomplete: boolean;
  /** True when the user stopped the turn mid-flight via the stop
   *  button (chat.message.cancel RPC). Partial state (completed
   *  rounds, tool calls so far) is preserved; the TurnBubble renders
   *  a subtle stop icon to make it clear the turn didn't finish
   *  organically. Distinct from ``incomplete`` which covers unintended
   *  cutoffs. */
  interrupted?: boolean;
  /** True while the turn is being built from streaming events. The
   *  current round's reasoning pulses; previous rounds and the final
   *  answer (if any yet) are static. Cleared once the
   *  ``chat.message.send`` RPC resolves and the turn is committed. */
  streaming?: boolean;
  /** Token + cost totals for this turn. Populated by the server
   *  (``turn_usage`` on the committed turn, or summed across
   *  ``rounds[].usage`` + ``final_usage`` on history replay). ``null``
   *  when no rounds recorded usage (old conversations, or a pre-AI
   *  error turn). */
  turn_usage?: TurnUsage | null;
  /** The final end_turn/max_tokens round's usage. Only set on history
   *  replay — live turns fold this into ``turn_usage`` directly. */
  final_usage?: RoundUsage;
}
