"""Greeting service — personalized arrival greetings via presence events.

Listens for ``presence.arrived`` events and announces a unique greeting
over speakers using TTS. Tracks who has been greeted today to avoid
repeats. Greeting text is generated by the AI service.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import UTC, datetime
from typing import Any

from gilbert.interfaces.ai import AIProvider, AISamplingProvider, Message, MessageRole
from gilbert.interfaces.auth import UserContext
from gilbert.interfaces.configuration import ConfigParam
from gilbert.interfaces.events import Event, EventBus, EventBusProvider
from gilbert.interfaces.feeds import FeedsProvider
from gilbert.interfaces.presence import PresenceProvider
from gilbert.interfaces.service import Service, ServiceInfo, ServiceResolver
from gilbert.interfaces.speaker import SpeakerProvider
from gilbert.interfaces.storage import StorageProvider
from gilbert.interfaces.tools import (
    ToolDefinition,
    ToolParameter,
    ToolParameterType,
)
from gilbert.interfaces.users import UserManagementProvider
from gilbert.interfaces.weather import (
    LocationNotConfiguredError,
    WeatherProvider,
    WeatherUnavailableError,
    WeatherUnits,
)

logger = logging.getLogger(__name__)

_GREETING_COLLECTION = "greeting_state"

# Manual ``/greet`` only uses the resolved user_id when the match
# confidence clears this bar. Below the threshold we still greet by
# the raw name, but don't pull recent-greeting history or mark anyone
# as greeted — those are user-keyed records and we'd rather drop them
# than attribute them to the wrong person.
_GREETING_MATCH_CONFIDENCE_THRESHOLD: float = 0.7

# Default template for the manual ``/greet`` AI prompt. The live value
# is read from ``greeting.enhanced_greeting_prompt`` and cached on
# ``self._enhanced_greeting_prompt`` so the Settings UI can tune it
# without a restart. Placeholders are filled with ``.format_map`` —
# missing ones in a user-edited version render empty, malformed
# templates fall back to this default at call time.
_DEFAULT_ENHANCED_GREETING_PROMPT = """\
Generate a personalized morning greeting for {name}. You're Gilbert, an AI \
assistant at a business — feel free to use any read-only data-lookup tools \
available to you (presence, recent activity, project status, time logs, etc.) \
to gather context that could make the greeting feel personal. Vary your tone \
across days (witty, warm, dramatic, deadpan, poetic, nerdy, etc.). Mention \
their name. 1-2 sentences.

Do NOT call any tool that broadcasts, announces, sends a message, or plays \
audio — the greeting is delivered separately by the calling code. Reply with \
ONLY the greeting text — no quotes, no preamble, no commentary on which tools \
you used.{style_instruction}{avoid_section}"""

_DEFAULT_WEATHER_HINT_TEMPLATE = (
    "Current weather at {location_name}: {temperature:.0f}{temp_suffix} "
    "{condition_phrase}, wind {wind_speed:.0f}{speed_suffix}"
    "{feels_like_clause}. Mention it casually if it fits the moment, "
    "otherwise ignore. Quote only the values shown — never invent additional "
    "weather details."
)


class GreetingService(Service):
    """Personalized arrival greetings driven by presence events.

    Capabilities: greeting
    """

    def __init__(self) -> None:
        self._enabled: bool = False
        self._event_bus: EventBus | None = None
        self._storage_backend: Any = None  # StorageBackend
        self._ai: Any = None  # AIService
        self._speaker: Any = None  # SpeakerService
        self._resolver: ServiceResolver | None = None
        self._unsubscribe: Any = None
        # Per-user lock prevents concurrent presence events from
        # double-greeting the same person (TOCTOU on _has_been_greeted).
        self._greeting_locks: dict[str, asyncio.Lock] = {}
        self._greeting_locks_guard = asyncio.Lock()

        # Config
        self._start_hour: int = 6
        self._cutoff_hour: int = 14
        self._style: str = ""
        self._speakers: list[str] = []
        self._timezone: str = "UTC"
        self._ai_profile: str = "light"
        self._enhanced_greeting_prompt: str = _DEFAULT_ENHANCED_GREETING_PROMPT
        self._include_weather: bool = True
        self._weather_hint_template: str = _DEFAULT_WEATHER_HINT_TEMPLATE
        self._weather: WeatherProvider | None = None
        self._include_briefing: bool = False
        self._briefing_max_seconds: int = 60
        self._feeds: FeedsProvider | None = None

    def service_info(self) -> ServiceInfo:
        return ServiceInfo(
            name="greeting",
            capabilities=frozenset({"greeting", "ai_tools"}),
            requires=frozenset({"event_bus", "entity_storage"}),
            optional=frozenset(
                {
                    "ai",
                    "speaker_control",
                    "text_to_speech",
                    "presence",
                    "configuration",
                    "feeds",
                }
            ),
            ai_calls=frozenset({"greeting"}),
            events=frozenset({"greeting.announced"}),
            toggleable=True,
            toggle_description="Automated greeting announcements",
        )

    async def start(self, resolver: ServiceResolver) -> None:
        self._resolver = resolver

        # Check enabled
        config_svc = resolver.get_capability("configuration")
        if config_svc is not None:
            from gilbert.interfaces.configuration import ConfigurationReader

            if isinstance(config_svc, ConfigurationReader):
                section = config_svc.get_section(self.config_namespace)
                if not section.get("enabled", False):
                    logger.info("Greeting service disabled")
                    return

        self._enabled = True

        # Get event bus and subscribe
        event_bus_svc = resolver.require_capability("event_bus")
        if not isinstance(event_bus_svc, EventBusProvider):
            raise RuntimeError("event_bus capability does not satisfy EventBusProvider")
        self._event_bus = event_bus_svc.bus
        self._unsubscribe = self._event_bus.subscribe("presence.arrived", self._on_arrival)

        # Entity storage for dedup tracking
        storage_svc = resolver.require_capability("entity_storage")
        if isinstance(storage_svc, StorageProvider):
            self._storage_backend = storage_svc.backend

        # Load config
        if config_svc is not None:
            from gilbert.interfaces.configuration import ConfigurationReader

            if isinstance(config_svc, ConfigurationReader):
                section = config_svc.get_section(self.config_namespace)
                self._start_hour = int(section.get("start_hour", 6))
                self._cutoff_hour = int(section.get("cutoff_hour", 14))
                self._style = section.get("style", "")
                self._speakers = section.get("speakers", [])
                self._timezone = section.get("timezone", "UTC")
                self._enhanced_greeting_prompt = (
                    section.get("enhanced_greeting_prompt") or _DEFAULT_ENHANCED_GREETING_PROMPT
                )
                self._include_weather = bool(
                    section.get("include_weather", self._include_weather)
                )
                self._weather_hint_template = section.get(
                    "weather_hint_template",
                    self._weather_hint_template,
                ) or _DEFAULT_WEATHER_HINT_TEMPLATE
                self._include_briefing = bool(
                    section.get("include_briefing", self._include_briefing)
                )
                self._briefing_max_seconds = int(
                    section.get("briefing_max_seconds", self._briefing_max_seconds)
                    or self._briefing_max_seconds
                )

        # Optional weather provider — if missing or wrong protocol,
        # degrade to the no-weather greeting.
        weather_svc = resolver.get_capability("weather")
        if isinstance(weather_svc, WeatherProvider):
            self._weather = weather_svc

        feeds_svc = resolver.get_capability("feeds")
        if isinstance(feeds_svc, FeedsProvider):
            self._feeds = feeds_svc

        # Schedule a one-shot check for people already present at startup.
        # This handles the case where Gilbert restarts while people are
        # already at the shop — they won't get a presence.arrived event
        # because the presence service suppresses events for users seen
        # on the first poll.
        scheduler = resolver.get_capability("scheduler")
        if scheduler is not None:
            from gilbert.interfaces.scheduler import Schedule, SchedulerProvider

            if isinstance(scheduler, SchedulerProvider):
                scheduler.add_job(
                    name="greeting-startup-check",
                    schedule=Schedule.once_after(45),
                    callback=self._greet_already_present,
                    system=True,
                )

        logger.info(
            "Greeting service started (window=%d:00-%d:00)",
            self._start_hour,
            self._cutoff_hour,
        )

    async def stop(self) -> None:
        if self._unsubscribe:
            self._unsubscribe()

    # --- Configurable protocol ---

    @property
    def config_namespace(self) -> str:
        return "greeting"

    @property
    def config_category(self) -> str:
        return "Communication"

    def config_params(self) -> list[ConfigParam]:
        return [
            ConfigParam(
                key="start_hour",
                type=ToolParameterType.INTEGER,
                description="Hour of day to start greeting (0-23).",
                default=6,
            ),
            ConfigParam(
                key="cutoff_hour",
                type=ToolParameterType.INTEGER,
                description="Hour of day to stop greeting (0-23).",
                default=14,
            ),
            ConfigParam(
                key="timezone",
                type=ToolParameterType.STRING,
                description="Timezone for greeting window.",
                default="UTC",
            ),
            ConfigParam(
                key="style",
                type=ToolParameterType.STRING,
                description="Custom style instructions for AI greeting generation.",
                default="",
                multiline=True,
                ai_prompt=True,
            ),
            ConfigParam(
                key="speakers",
                type=ToolParameterType.ARRAY,
                description="Speaker names for announcements (empty = all).",
                default=[],
                choices_from="speakers",
            ),
            ConfigParam(
                key="ai_profile",
                type=ToolParameterType.STRING,
                description="AI profile for greeting generation.",
                default="light",
                choices_from="ai_profiles",
            ),
            ConfigParam(
                key="include_weather",
                type=ToolParameterType.BOOLEAN,
                description=(
                    "Enrich greetings with a one-line weather hint when "
                    "the WeatherService is available."
                ),
                default=True,
            ),
            ConfigParam(
                key="weather_hint_template",
                type=ToolParameterType.STRING,
                description=(
                    "Python str.format template for the weather hint "
                    "blurb interpolated into the greeting prompt. "
                    "Available placeholders: {location_name}, "
                    "{temperature}, {temp_suffix}, {condition_phrase}, "
                    "{wind_speed}, {speed_suffix}, {feels_like_clause}."
                ),
                default=_DEFAULT_WEATHER_HINT_TEMPLATE,
                multiline=True,
                ai_prompt=True,
            ),
            ConfigParam(
                key="include_briefing",
                type=ToolParameterType.BOOLEAN,
                description=(
                    "When the FeedsProvider capability is available and "
                    "the user hasn't been briefed today, splice the "
                    "news briefing into the arrival greeting."
                ),
                default=False,
            ),
            ConfigParam(
                key="briefing_max_seconds",
                type=ToolParameterType.INTEGER,
                description=(
                    "Soft cap on the briefing length passed as a hint "
                    "into the briefing AI call (~2.5 words/sec)."
                ),
                default=60,
            ),
            ConfigParam(
                key="enhanced_greeting_prompt",
                type=ToolParameterType.STRING,
                description=(
                    "Prompt template for the manual /greet tool (the path that "
                    "lets the AI use data-lookup tools to personalize the "
                    "greeting). Placeholders: {name}, {style_instruction}, "
                    "{avoid_section}."
                ),
                default=_DEFAULT_ENHANCED_GREETING_PROMPT,
                multiline=True,
                ai_prompt=True,
            ),
        ]

    async def on_config_changed(self, config: dict[str, Any]) -> None:
        self._start_hour = int(config.get("start_hour", self._start_hour))
        self._cutoff_hour = int(config.get("cutoff_hour", self._cutoff_hour))
        self._style = config.get("style", self._style)
        self._ai_profile = config.get("ai_profile", self._ai_profile)
        self._speakers = config.get("speakers", self._speakers)
        self._timezone = config.get("timezone", self._timezone)
        self._include_weather = bool(
            config.get("include_weather", self._include_weather)
        )
        self._weather_hint_template = config.get(
            "weather_hint_template",
            self._weather_hint_template,
        ) or _DEFAULT_WEATHER_HINT_TEMPLATE
        self._include_briefing = bool(
            config.get("include_briefing", self._include_briefing)
        )
        self._briefing_max_seconds = int(
            config.get("briefing_max_seconds", self._briefing_max_seconds)
            or self._briefing_max_seconds
        )
        if "enhanced_greeting_prompt" in config:
            # Empty string explicitly clears back to the bundled default.
            self._enhanced_greeting_prompt = (
                config["enhanced_greeting_prompt"] or _DEFAULT_ENHANCED_GREETING_PROMPT
            )

    async def _greet_already_present(self) -> None:
        """Greet anyone already present at startup who hasn't been greeted today.

        Instead of greeting each person individually (which would cause
        announcements to step on each other), generates a single combined
        greeting for everyone present.

        Marks users as greeted BEFORE announcing so any concurrent
        ``presence.arrived`` event (which can fire seconds after the
        startup poll) sees them as already greeted and doesn't pile on.
        """
        if not self._in_greeting_window():
            logger.info("Startup greeting skipped — outside greeting window")
            return

        presence_svc = self._resolver.get_capability("presence") if self._resolver else None
        if not isinstance(presence_svc, PresenceProvider):
            logger.info("Startup greeting skipped — no presence service")
            return

        try:
            here = await presence_svc.who_is_here()
        except Exception:
            logger.warning("Startup greeting: could not check who is here", exc_info=True)
            return

        # Filter to people not yet greeted today
        to_greet_names: list[str] = []
        to_greet_ids: list[str] = []
        for p in here:
            if not await self._has_been_greeted_today(p.user_id):
                name = await self._get_display_name(p.user_id)
                to_greet_names.append(name)
                to_greet_ids.append(p.user_id)

        logger.info(
            "Startup greeting: %d present, %d to greet",
            len(here),
            len(to_greet_names),
        )

        if not to_greet_names:
            return

        # Mark as greeted FIRST — before AI generation and announce —
        # so concurrent _on_arrival handlers see the flag immediately.
        for uid in to_greet_ids:
            await self._mark_greeted(uid, "")

        # Collect recent greetings across all users for variety
        all_recent: list[str] = []
        for p in here:
            all_recent.extend(await self._get_recent_greetings(p.user_id))

        # Generate a single combined greeting
        greeting = await self._generate_group_greeting(to_greet_names, all_recent)
        logger.info("Startup greeting: %s", greeting)

        await self._announce(greeting)

        # Update the greeting text now that we have it
        for uid in to_greet_ids:
            await self._mark_greeted(uid, greeting)

        if self._event_bus:
            await self._event_bus.publish(
                Event(
                    event_type="greeting.announced",
                    data={
                        "names": to_greet_names,
                        "greeting": greeting,
                        "startup": True,
                    },
                    source="greeting",
                )
            )

    async def _on_arrival(self, event: Event) -> None:
        """Handle a presence.arrived event."""
        user_id = event.data.get("user_id", "")
        if not user_id:
            return
        if not self._in_greeting_window():
            return
        await self._greet_user(user_id)

    async def _greet_user(self, user_id: str) -> None:
        """Greet a user if they haven't been greeted today.

        Serialized per-user so concurrent ``presence.arrived`` events
        for the same person can't race past the greeted-today check.
        """
        # Get or create per-user lock
        async with self._greeting_locks_guard:
            if user_id not in self._greeting_locks:
                self._greeting_locks[user_id] = asyncio.Lock()
            lock = self._greeting_locks[user_id]

        async with lock:
            if await self._has_been_greeted_today(user_id):
                return

            display_name = await self._get_display_name(user_id)
            recent = await self._get_recent_greetings(user_id)
            greeting = await self._generate_greeting(display_name, recent)

            briefing_appendix = await self._maybe_briefing_text(user_id)
            announcement = (
                f"{greeting} {briefing_appendix}".strip()
                if briefing_appendix
                else greeting
            )

            logger.info("Greeting %s: %s", user_id, announcement)

            await self._mark_greeted(user_id, greeting)
            await self._announce(announcement)

            if self._event_bus:
                await self._event_bus.publish(
                    Event(
                        event_type="greeting.announced",
                        data={
                            "user_id": user_id,
                            "greeting": greeting,
                            "briefing_included": bool(briefing_appendix),
                        },
                        source="greeting",
                    )
                )

    async def _maybe_briefing_text(self, user_id: str) -> str:
        """Build the briefing text to splice into a greeting, if configured."""
        if not self._include_briefing or self._feeds is None:
            return ""
        if self._storage_backend is None:
            return ""

        state = await self._storage_backend.get("feed_briefing_state", user_id)
        today = self._today_str()
        if state and state.get("last_briefed_on") == today:
            return ""

        user_ctx = UserContext(
            user_id=user_id,
            email=f"{user_id}@local",
            display_name=user_id,
            roles=frozenset({"user"}),
        )
        try:
            result = await self._feeds.build_briefing(
                user_ctx,
                top_n=3,
                max_spoken_seconds=self._briefing_max_seconds,
                mark_briefed=True,
            )
        except Exception:
            logger.warning(
                "greeting: build_briefing failed for %s",
                user_id,
                exc_info=True,
            )
            return ""

        return (getattr(result, "spoken", "") or "").strip()

    def _in_greeting_window(self) -> bool:
        """Check if current time is within the greeting window."""
        try:
            from zoneinfo import ZoneInfo

            now = datetime.now(ZoneInfo(self._timezone))
        except Exception:
            now = datetime.now(UTC)

        return self._start_hour <= now.hour < self._cutoff_hour

    async def _get_display_name(self, user_id: str) -> str:
        """Resolve a user_id to a display-friendly first name."""
        from gilbert.core.user_utils import resolve_display_name

        return await resolve_display_name(user_id, self._resolver, first_name_only=True)

    async def _has_been_greeted_today(self, user_id: str) -> bool:
        """Check if user has been greeted today."""
        if self._storage_backend is None:
            return False

        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        if not record:
            return False

        today = self._today_str()
        return bool(record.get("last_greeting_date") == today)

    async def _mark_greeted(self, user_id: str, greeting: str = "") -> None:
        """Mark user as greeted today and store the greeting text."""
        if self._storage_backend is None:
            return

        today = self._today_str()
        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        count = (record.get("greeting_count", 0) if record else 0) + 1

        # Keep a rolling log of recent greetings so the AI can avoid repeats
        recent: list[str] = record.get("recent_greetings", []) if record else []
        if greeting:
            recent.append(greeting)
            recent = recent[-10:]  # keep last 10

        await self._storage_backend.put(
            _GREETING_COLLECTION,
            user_id,
            {
                "user_id": user_id,
                "last_greeting_date": today,
                "greeting_count": count,
                "recent_greetings": recent,
            },
        )

    async def _get_recent_greetings(self, user_id: str) -> list[str]:
        """Get recent greeting texts for a user (for anti-repetition)."""
        if self._storage_backend is None:
            return []
        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        if not record:
            return []
        recent = record.get("recent_greetings", [])
        return list(recent) if isinstance(recent, list) else []

    def _today_str(self) -> str:
        """Get today's date string in the configured timezone."""
        try:
            from zoneinfo import ZoneInfo

            return datetime.now(ZoneInfo(self._timezone)).strftime("%Y-%m-%d")
        except Exception:
            return datetime.now(UTC).strftime("%Y-%m-%d")

    async def _build_weather_blurb(self, user: UserContext | None = None) -> str:
        """Build a deterministic one-line weather blurb for the greeting prompt."""
        if not self._include_weather or self._weather is None:
            return ""
        try:
            current = await self._weather.get_current(user=user)
        except LocationNotConfiguredError:
            return ""
        except WeatherUnavailableError:
            logger.debug("Weather backend unavailable for greeting; skipping blurb")
            return ""

        temp_suffix = "°F" if current.units is WeatherUnits.IMPERIAL else "°C"
        speed_suffix = "mph" if current.units is WeatherUnits.IMPERIAL else "km/h"
        condition_phrase = current.condition.value.replace("_", " ")
        feels_like_clause = ""
        if (
            current.feels_like is not None
            and abs(current.feels_like - current.temperature) >= 3
        ):
            feels_like_clause = f", feels like {current.feels_like:.0f}{temp_suffix}"
        location_name = current.location.name or "the configured location"

        try:
            return self._weather_hint_template.format(
                location_name=location_name,
                temperature=current.temperature,
                temp_suffix=temp_suffix,
                condition_phrase=condition_phrase,
                wind_speed=current.wind_speed,
                speed_suffix=speed_suffix,
                feels_like_clause=feels_like_clause,
            )
        except (KeyError, IndexError, ValueError):
            logger.warning("Greeting weather_hint_template format failed", exc_info=True)
            return ""

    async def _generate_greeting(self, name: str, recent: list[str] | None = None) -> str:
        """Generate a personalized greeting via AI, with fallback."""
        if self._resolver is None:
            return f"Good morning, {name}!"

        ai_svc = self._resolver.get_capability("ai_chat")
        if not isinstance(ai_svc, AISamplingProvider):
            return f"Good morning, {name}!"

        style_instruction = ""
        if self._style:
            style_instruction = f"\nStyle: {self._style}."

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nHere are your recent greetings — do NOT repeat or closely "
                "paraphrase any of these. Be completely different in tone, "
                "structure, and word choice:\n" + "\n".join(f"- {g}" for g in recent[-7:])
            )

        weather_blurb = await self._build_weather_blurb(user=None)
        weather_section = f"\n\nContext: {weather_blurb}" if weather_blurb else ""

        prompt = (
            f"Generate a morning greeting for {name} who just arrived at the shop. "
            f"You're Gilbert, an AI assistant at a business. Be creative — vary your "
            f"tone across days (witty, warm, dramatic, deadpan, poetic, nerdy, etc.). "
            f"Mention their name. 1-2 sentences max. "
            f"Write ONLY the greeting — no quotes, no preamble."
            f"{style_instruction}{weather_section}{avoid_section}"
        )

        # tools_override=[] forces a zero-tool call regardless of the
        # profile's tool_mode, so the model can't accidentally call
        # `announce` (or anything else) as a side effect of generating
        # greeting text. Profile is still used for backend/model choice.
        try:
            response = await ai_svc.complete_one_shot(
                messages=[Message(role=MessageRole.USER, content=prompt)],
                profile_name=self._ai_profile,
                tools_override=[],
            )
            text = response.message.content.strip()
            if text and len(text) < 500:
                return text
        except Exception:
            logger.warning("AI greeting generation failed", exc_info=True)

        return f"Good morning, {name}!"

    async def _generate_group_greeting(
        self, names: list[str], recent: list[str] | None = None
    ) -> str:
        """Generate a single greeting for multiple people."""
        if len(names) == 1:
            return await self._generate_greeting(names[0], recent)

        if self._resolver is None:
            return f"Good morning, {', '.join(names)}!"

        ai_svc = self._resolver.get_capability("ai_chat")
        if not isinstance(ai_svc, AISamplingProvider):
            return f"Good morning, {', '.join(names)}!"

        style_instruction = ""
        if self._style:
            style_instruction = f"\nStyle: {self._style}."

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nHere are recent greetings — do NOT repeat or closely "
                "paraphrase any of these. Be completely different:\n"
                + "\n".join(f"- {g}" for g in recent[-7:])
            )

        names_str = ", ".join(names[:-1]) + f", and {names[-1]}"
        prompt = (
            f"Generate a morning greeting for the crew: {names_str}. "
            f"You're Gilbert, an AI assistant at a business. Greet them as a group "
            f"with personality — vary your tone (witty, warm, dramatic, deadpan, etc.). "
            f"Mention a few names naturally. 2-3 sentences max. "
            f"Write ONLY the greeting."
            f"{style_instruction}{avoid_section}"
        )

        try:
            response = await ai_svc.complete_one_shot(
                messages=[Message(role=MessageRole.USER, content=prompt)],
                profile_name=self._ai_profile,
                tools_override=[],
            )
            text = response.message.content.strip()
            if text and len(text) < 500:
                return text
        except Exception:
            logger.warning("AI group greeting failed", exc_info=True)

        return f"Good morning, {names_str}!"

    async def _resolve_user_match(self, name: str) -> Any:
        """Delegate name → user lookup to the user service.

        Returns the ``NameMatch`` (with ``user_id`` + ``confidence``)
        or ``None`` when the resolver isn't wired, the user service
        isn't around, or the lookup didn't find a unique match.
        """
        if not name or self._resolver is None:
            return None
        users_svc = self._resolver.get_capability("users")
        if not isinstance(users_svc, UserManagementProvider):
            return None
        try:
            return await users_svc.resolve_user_id_by_name(name)
        except Exception:
            logger.debug("greet: resolve_user_id_by_name failed", exc_info=True)
            return None

    async def _generate_greeting_enhanced(
        self, name: str, recent: list[str] | None = None
    ) -> str:
        """Generate a personalized greeting with full tool access.

        Unlike ``_generate_greeting`` (used by the automatic arrival
        paths, which forces ``tools_override=[]`` so the model can't
        accidentally call ``announce`` while generating greeting text),
        this path runs ``ai_svc.chat()`` against the configured
        ``ai_profile`` with its tools intact. That lets the model
        consult whatever data-lookup tools the profile exposes —
        recent activity, time logs, presence, project status, etc. —
        before writing the greeting.

        The prompt template is the configurable
        ``greeting.enhanced_greeting_prompt`` setting (falls back to
        the bundled default if the user clears it or formatting fails);
        a soft prompt-level guardrail asks the model to stick to
        read-only data-lookup tools. On any failure we fall back to a
        plain ``"Good morning, <name>!"``.
        """
        if self._resolver is None:
            return f"Good morning, {name}!"
        ai_svc = self._resolver.get_capability("ai_chat")
        if not isinstance(ai_svc, AIProvider):
            return f"Good morning, {name}!"

        style_instruction = ""
        if self._style:
            style_instruction = f"\nStyle: {self._style}."

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nRecent greetings — do NOT repeat or closely paraphrase any "
                "of these. Be completely different in tone, structure, and word "
                "choice:\n" + "\n".join(f"- {g}" for g in recent[-7:])
            )

        subs = {
            "name": name,
            "style_instruction": style_instruction,
            "avoid_section": avoid_section,
        }
        try:
            prompt = self._enhanced_greeting_prompt.format_map(subs)
        except (KeyError, IndexError, ValueError):
            # User-edited template had a bad placeholder — fall back to
            # the bundled default so /greet keeps working until they fix
            # the saved value.
            logger.warning(
                "Enhanced greeting prompt failed to format; falling back to default",
                exc_info=True,
            )
            prompt = _DEFAULT_ENHANCED_GREETING_PROMPT.format_map(subs)

        try:
            result = await ai_svc.chat(
                user_message=prompt,
                user_ctx=UserContext.SYSTEM,
                ai_call="greeting",
                ai_profile=self._ai_profile,
            )
            text = (result.response_text or "").strip()
            if text and len(text) < 500:
                return text
        except Exception:
            logger.warning("Enhanced AI greeting generation failed", exc_info=True)

        return f"Good morning, {name}!"

    # ── ToolProvider Protocol ───────────────────────────────────

    @property
    def tool_provider_name(self) -> str:
        return "greeting"

    def get_tools(self, user_ctx: UserContext | None = None) -> list[ToolDefinition]:
        if not self._enabled:
            return []
        return [
            ToolDefinition(
                name="greet",
                slash_command="greet",
                slash_help="Announce a personalized greeting: /greet <name>",
                description=(
                    "Generate and announce a personalized greeting for someone. "
                    "Use this when a user asks you to greet someone or welcome them."
                ),
                parameters=[
                    ToolParameter(
                        name="name",
                        type=ToolParameterType.STRING,
                        description="Name of the person to greet.",
                    ),
                ],
                required_role="user",
            ),
        ]

    async def execute_tool(self, name: str, arguments: dict[str, Any]) -> str:
        if name != "greet":
            raise KeyError(f"Unknown tool: {name}")

        person_name = arguments.get("name", "").strip()
        if not person_name:
            return "I need a name to greet."

        # Resolve the input to a user_id when we can — that unlocks
        # recent-greetings deduplication and the "marked greeted today"
        # bookkeeping. Threshold on confidence so a weak email-local
        # match for the wrong person doesn't smear their greeting
        # history. Below threshold, we still greet by name — the AI
        # just doesn't get history and we don't mark anyone.
        match = await self._resolve_user_match(person_name)
        user_id: str | None = None
        display_name = person_name
        if match is not None and match.confidence >= _GREETING_MATCH_CONFIDENCE_THRESHOLD:
            user_id = match.user_id
            display_name = await self._get_display_name(user_id)

        recent = await self._get_recent_greetings(user_id) if user_id else []

        greeting = await self._generate_greeting_enhanced(display_name, recent)

        if user_id:
            await self._mark_greeted(user_id, greeting)

        await self._announce(greeting)

        return f'Greeted {display_name}: "{greeting}"'

    # ── Announce ────────────────────────────────────────────────

    async def _announce(self, text: str) -> None:
        """Announce greeting via speakers."""
        if self._resolver is None:
            return

        speaker_svc = self._resolver.get_capability("speaker_control")
        if not isinstance(speaker_svc, SpeakerProvider):
            logger.debug("No speaker service — greeting not announced: %s", text)
            return

        try:
            await speaker_svc.announce(
                text,
                speaker_names=self._speakers or None,
                context="Cheery welcome greeting for someone arriving at the shop",
            )
        except Exception:
            logger.warning("Failed to announce greeting", exc_info=True)
