"""Greeting service — personalized arrival greetings via presence events.

Listens for ``presence.arrived`` events and announces a unique greeting
over speakers using TTS. Tracks who has been greeted today to avoid
repeats. Greeting text is generated by the AI service.
"""

from __future__ import annotations

import asyncio
import logging
from datetime import UTC, datetime
from typing import Any

from gilbert.interfaces.ai import AIProvider, AISamplingProvider, Message, MessageRole
from gilbert.interfaces.auth import UserContext
from gilbert.interfaces.configuration import ConfigParam
from gilbert.interfaces.events import Event, EventBus, EventBusProvider
from gilbert.interfaces.greeting import GreetingContext, GreetingContextProvider
from gilbert.interfaces.presence import PresenceProvider
from gilbert.interfaces.service import Service, ServiceInfo, ServiceResolver
from gilbert.interfaces.speaker import SpeakerProvider
from gilbert.interfaces.storage import StorageProvider
from gilbert.interfaces.tools import (
    ToolDefinition,
    ToolParameter,
    ToolParameterType,
)
from gilbert.interfaces.users import UserManagementProvider

logger = logging.getLogger(__name__)

_GREETING_COLLECTION = "greeting_state"
_CAMERA_MUTES_COLLECTION = "camera_mutes"

# Manual ``/greet`` only uses the resolved user_id when the match
# confidence clears this bar. Below the threshold we still greet by
# the raw name, but don't pull recent-greeting history or mark anyone
# as greeted — those are user-keyed records and we'd rather drop them
# than attribute them to the wrong person.
_GREETING_MATCH_CONFIDENCE_THRESHOLD: float = 0.7

# Default template for the manual ``/greet`` AI prompt. The live value
# is read from ``greeting.enhanced_greeting_prompt`` and cached on
# ``self._enhanced_greeting_prompt`` so the Settings UI can tune it
# without a restart. Placeholders are filled with ``.format_map`` —
# missing ones in a user-edited version render empty, malformed
# templates fall back to this default at call time.
_DEFAULT_ENHANCED_GREETING_PROMPT = """\
Generate a personalized morning greeting for {name}. You're Gilbert, an AI \
assistant at a business — feel free to use any read-only data-lookup tools \
available to you (presence, recent activity, project status, time logs, etc.) \
to gather context that could make the greeting feel personal. Vary your tone \
across days (witty, warm, dramatic, deadpan, poetic, nerdy, etc.). Mention \
their name. 1-2 sentences.

Do NOT call any tool that broadcasts, announces, sends a message, or plays \
audio — the greeting is delivered separately by the calling code. Reply with \
ONLY the greeting text — no quotes, no preamble, no commentary on which tools \
you used.{style_instruction}{avoid_section}"""

_DEFAULT_ARRIVAL_GREETING_PROMPT = """\
Generate a morning greeting for {name} who just arrived at the shop. \
You're Gilbert, an AI assistant at a business. Be creative — vary your \
tone across days (witty, warm, dramatic, deadpan, poetic, nerdy, etc.). \
Mention their name. 1-2 sentences max. Write ONLY the greeting — no \
quotes, no preamble.{style_instruction}{context_section}{avoid_section}"""

_DEFAULT_WEATHER_HINT_TEMPLATE = (
    "Current weather at {location_name}: {temperature:.0f}{temp_suffix} "
    "{condition_phrase}, wind {wind_speed:.0f}{speed_suffix}"
    "{feels_like_clause}. Mention it casually if it fits the moment, "
    "otherwise ignore. Quote only the values shown — never invent additional "
    "weather details."
)

_DEFAULT_CAMERA_ANNOUNCE_PROMPT = (
    "Generate one short alert sentence (under 12 words) that announces a "
    "{label} event at the {camera} camera. Use the time of day if it is "
    "relevant ({time_of_day}: late_night, morning, midday, evening). Vary "
    "the phrasing across calls — don't always start with \"There's…\". No "
    "emoji. No hedging. Pick a tone consistent with the label: package = "
    "warm and informative; person = neutral observation; glass_break / "
    "smoke = brief and urgent."
)

_DEFAULT_ANNOUNCE_CAMERA_LABELS: tuple[str, ...] = ("package",)
_DEFAULT_CAMERA_ANNOUNCE_DEDUP_SECONDS = 300.0
_DEFAULT_CAMERA_ANNOUNCE_DEDUP_KEYS: dict[str, list[str]] = {
    "package": ["label"],
    "person": ["label", "zone_group"],
}


class GreetingService(Service):
    """Personalized arrival greetings driven by presence events.

    Capabilities: greeting
    """

    def __init__(self) -> None:
        self._enabled: bool = False
        self._event_bus: EventBus | None = None
        self._storage_backend: Any = None  # StorageBackend
        self._ai: Any = None  # AIService
        self._speaker: Any = None  # SpeakerService
        self._resolver: ServiceResolver | None = None
        self._unsubscribe: Any = None
        # Per-user lock prevents concurrent presence events from
        # double-greeting the same person (TOCTOU on _has_been_greeted).
        self._greeting_locks: dict[str, asyncio.Lock] = {}
        self._greeting_locks_guard = asyncio.Lock()

        # Config
        self._start_hour: int = 6
        self._cutoff_hour: int = 14
        self._style: str = ""
        self._speakers: list[str] = []
        self._timezone: str = "UTC"
        self._ai_profile: str = "light"
        self._enhanced_greeting_prompt: str = _DEFAULT_ENHANCED_GREETING_PROMPT
        self._arrival_greeting_prompt: str = _DEFAULT_ARRIVAL_GREETING_PROMPT

        # Context provider discovery and assembly
        self._enabled_context_providers: list[str] | None = None  # None = "all"
        self._context_providers: list[GreetingContextProvider] = []

        # Camera-event announcement config + state.
        self._announce_camera_labels: tuple[str, ...] = (
            _DEFAULT_ANNOUNCE_CAMERA_LABELS
        )
        self._camera_announce_dedup_seconds: float = (
            _DEFAULT_CAMERA_ANNOUNCE_DEDUP_SECONDS
        )
        self._camera_announce_dedup_keys: dict[str, list[str]] = dict(
            _DEFAULT_CAMERA_ANNOUNCE_DEDUP_KEYS
        )
        self._camera_zone_groups: dict[str, list[str]] = {}
        self._camera_announce_prompt: str = _DEFAULT_CAMERA_ANNOUNCE_PROMPT
        self._camera_announce_per_label_prompts: dict[str, str] = {}
        # Inverse map (camera -> zone_group) for fast dedup-key rendering.
        self._camera_to_zone_group: dict[str, str] = {}
        # In-memory dedup state: dedup_key -> last announce ts (epoch s).
        self._camera_announce_dedup_state: dict[str, float] = {}
        self._unsubscribe_camera: Any = None

    def service_info(self) -> ServiceInfo:
        return ServiceInfo(
            name="greeting",
            capabilities=frozenset({"greeting", "ai_tools", "ws_handlers"}),
            requires=frozenset({"event_bus", "entity_storage"}),
            optional=frozenset(
                {
                    "ai",
                    "speaker_control",
                    "text_to_speech",
                    "presence",
                    "configuration",
                }
            ),
            ai_calls=frozenset({"greeting"}),
            events=frozenset({"greeting.announced"}),
            toggleable=True,
            toggle_description="Automated greeting announcements",
        )

    async def start(self, resolver: ServiceResolver) -> None:
        self._resolver = resolver
        self._discover_context_providers()

        # Check enabled
        config_svc = resolver.get_capability("configuration")
        if config_svc is not None:
            from gilbert.interfaces.configuration import ConfigurationReader

            if isinstance(config_svc, ConfigurationReader):
                section = config_svc.get_section(self.config_namespace)
                if not section.get("enabled", False):
                    logger.info("Greeting service disabled")
                    return

        self._enabled = True

        # Get event bus and subscribe
        event_bus_svc = resolver.require_capability("event_bus")
        if not isinstance(event_bus_svc, EventBusProvider):
            raise RuntimeError("event_bus capability does not satisfy EventBusProvider")
        self._event_bus = event_bus_svc.bus
        self._unsubscribe = self._event_bus.subscribe("presence.arrived", self._on_arrival)
        # Camera-detected events fan-out for the announce path; per-label
        # config gates whether we actually announce.
        self._unsubscribe_camera = self._event_bus.subscribe(
            "camera.event.detected", self._on_camera_event
        )

        # Entity storage for dedup tracking
        storage_svc = resolver.require_capability("entity_storage")
        if isinstance(storage_svc, StorageProvider):
            self._storage_backend = storage_svc.backend

        # Load config
        if config_svc is not None:
            from gilbert.interfaces.configuration import ConfigurationReader

            if isinstance(config_svc, ConfigurationReader):
                section = config_svc.get_section(self.config_namespace)
                self._start_hour = int(section.get("start_hour", 6))
                self._cutoff_hour = int(section.get("cutoff_hour", 14))
                self._style = section.get("style", "")
                self._speakers = section.get("speakers", [])
                self._timezone = section.get("timezone", "UTC")
                self._enhanced_greeting_prompt = (
                    section.get("enhanced_greeting_prompt") or _DEFAULT_ENHANCED_GREETING_PROMPT
                )
                self._arrival_greeting_prompt = (
                    section.get("arrival_greeting_prompt") or _DEFAULT_ARRIVAL_GREETING_PROMPT
                )

        # Schedule a one-shot check for people already present at startup.
        # This handles the case where Gilbert restarts while people are
        # already at the shop — they won't get a presence.arrived event
        # because the presence service suppresses events for users seen
        # on the first poll.
        scheduler = resolver.get_capability("scheduler")
        if scheduler is not None:
            from gilbert.interfaces.scheduler import Schedule, SchedulerProvider

            if isinstance(scheduler, SchedulerProvider):
                scheduler.add_job(
                    name="greeting-startup-check",
                    schedule=Schedule.once_after(45),
                    callback=self._greet_already_present,
                    system=True,
                )

        logger.info(
            "Greeting service started (window=%d:00-%d:00)",
            self._start_hour,
            self._cutoff_hour,
        )

    async def stop(self) -> None:
        if self._unsubscribe:
            self._unsubscribe()
        if self._unsubscribe_camera:
            self._unsubscribe_camera()
            self._unsubscribe_camera = None

    # --- Configurable protocol ---

    @property
    def config_namespace(self) -> str:
        return "greeting"

    @property
    def config_category(self) -> str:
        return "Communication"

    def config_params(self) -> list[ConfigParam]:
        return [
            ConfigParam(
                key="start_hour",
                type=ToolParameterType.INTEGER,
                description="Hour of day to start greeting (0-23).",
                default=6,
            ),
            ConfigParam(
                key="cutoff_hour",
                type=ToolParameterType.INTEGER,
                description="Hour of day to stop greeting (0-23).",
                default=14,
            ),
            ConfigParam(
                key="timezone",
                type=ToolParameterType.STRING,
                description="Timezone for greeting window.",
                default="UTC",
            ),
            ConfigParam(
                key="style",
                type=ToolParameterType.STRING,
                description="Custom style instructions for AI greeting generation.",
                default="",
                multiline=True,
                ai_prompt=True,
            ),
            ConfigParam(
                key="speakers",
                type=ToolParameterType.ARRAY,
                description="Speaker names for announcements (empty = all).",
                default=[],
                choices_from="speakers",
            ),
            ConfigParam(
                key="ai_profile",
                type=ToolParameterType.STRING,
                description="AI profile for greeting generation.",
                default="light",
                choices_from="ai_profiles",
            ),
            ConfigParam(
                key="arrival_greeting_prompt",
                type=ToolParameterType.STRING,
                description=(
                    "Prompt template for the auto-generated arrival greeting. "
                    "Placeholders: {name}, {style_instruction}, {avoid_section}, "
                    "{context_section}. The context section is a labeled list "
                    "(\"Weather: ...\", \"Health: ...\", \"News briefing: ...\") "
                    "drawn from whichever GreetingContextProvider services are "
                    "enabled under enabled_context_providers — you can write "
                    "rules like \"always mention the weather if it's extreme.\""
                ),
                default=_DEFAULT_ARRIVAL_GREETING_PROMPT,
                multiline=True,
                ai_prompt=True,
            ),
            ConfigParam(
                key="enhanced_greeting_prompt",
                type=ToolParameterType.STRING,
                description=(
                    "Prompt template for the manual /greet tool (the path that "
                    "lets the AI use data-lookup tools to personalize the "
                    "greeting). Placeholders: {name}, {style_instruction}, "
                    "{avoid_section}."
                ),
                default=_DEFAULT_ENHANCED_GREETING_PROMPT,
                multiline=True,
                ai_prompt=True,
            ),
            ConfigParam(
                key="announce_camera_labels",
                type=ToolParameterType.ARRAY,
                description=(
                    "Labels to announce on camera.event.detected. "
                    "Default ``[\"package\"]`` — add ``person`` etc. "
                    "as opt-ins."
                ),
                default=list(_DEFAULT_ANNOUNCE_CAMERA_LABELS),
            ),
            ConfigParam(
                key="camera_announce_dedup_seconds",
                type=ToolParameterType.NUMBER,
                description=(
                    "Window in seconds for the camera-event dedup key "
                    "(default 300s)."
                ),
                default=_DEFAULT_CAMERA_ANNOUNCE_DEDUP_SECONDS,
            ),
            ConfigParam(
                key="camera_announce_dedup_keys",
                type=ToolParameterType.OBJECT,
                description=(
                    "Per-label dedup-key shape: "
                    "``{label: [\"label\"|\"camera\"|\"zone_group\", ...]}``. "
                    "Default ``{package: [label], person: [label, "
                    "zone_group]}`` so a single visitor across "
                    "adjacent cameras counts as one announce."
                ),
                default=dict(_DEFAULT_CAMERA_ANNOUNCE_DEDUP_KEYS),
            ),
            ConfigParam(
                key="camera_zone_groups",
                type=ToolParameterType.OBJECT,
                description=(
                    "Map a logical zone name to the cameras that "
                    "watch it: ``{front_entry: [driveway, "
                    "front_porch, front_door]}``. Cameras not listed "
                    "are their own one-element group."
                ),
                default={},
            ),
            ConfigParam(
                key="camera_announce_prompt",
                type=ToolParameterType.STRING,
                description=(
                    "Prompt template for the AI-generated camera-event "
                    "alert sentence. ``{label}``, ``{camera}``, "
                    "``{time_of_day}`` are interpolated."
                ),
                default=_DEFAULT_CAMERA_ANNOUNCE_PROMPT,
                multiline=True,
                ai_prompt=True,
            ),
            ConfigParam(
                key="camera_announce_per_label_prompts",
                type=ToolParameterType.OBJECT,
                description=(
                    "Per-label prompt overrides: "
                    "``{package: \"...\", person: \"...\", "
                    "glass_break: \"...\"}``. Tone differs by label."
                ),
                default={},
            ),
            ConfigParam(
                key="enabled_context_providers",
                type=ToolParameterType.ARRAY,
                description=(
                    "Which context providers to include in the available_context "
                    "block of the greeting prompt. Discovered providers — Weather, "
                    "News briefing, Health, etc. — appear here as toggleable rows. "
                    "Leave empty to disable all extras; omit (default) to include "
                    "every discovered provider."
                ),
                default=None,
            ),
        ]

    async def on_config_changed(self, config: dict[str, Any]) -> None:
        self._start_hour = int(config.get("start_hour", self._start_hour))
        self._cutoff_hour = int(config.get("cutoff_hour", self._cutoff_hour))
        self._style = config.get("style", self._style)
        self._ai_profile = config.get("ai_profile", self._ai_profile)
        self._speakers = config.get("speakers", self._speakers)
        self._timezone = config.get("timezone", self._timezone)
        if "arrival_greeting_prompt" in config:
            self._arrival_greeting_prompt = (
                config["arrival_greeting_prompt"] or _DEFAULT_ARRIVAL_GREETING_PROMPT
            )
        if "enhanced_greeting_prompt" in config:
            # Empty string explicitly clears back to the bundled default.
            self._enhanced_greeting_prompt = (
                config["enhanced_greeting_prompt"] or _DEFAULT_ENHANCED_GREETING_PROMPT
            )
        labels = config.get("announce_camera_labels")
        if isinstance(labels, list):
            self._announce_camera_labels = tuple(str(label) for label in labels)
        try:
            self._camera_announce_dedup_seconds = float(
                config.get(
                    "camera_announce_dedup_seconds",
                    self._camera_announce_dedup_seconds,
                )
            )
        except (TypeError, ValueError):
            self._camera_announce_dedup_seconds = (
                _DEFAULT_CAMERA_ANNOUNCE_DEDUP_SECONDS
            )
        keys = config.get("camera_announce_dedup_keys")
        if isinstance(keys, dict):
            self._camera_announce_dedup_keys = {
                str(k): [str(part) for part in v if isinstance(part, str)]
                for k, v in keys.items()
                if isinstance(v, list)
            }
        zone_groups = config.get("camera_zone_groups")
        if isinstance(zone_groups, dict):
            self._camera_zone_groups = {
                str(g): [str(c) for c in cams if isinstance(c, str)]
                for g, cams in zone_groups.items()
                if isinstance(cams, list)
            }
            inverse: dict[str, str] = {}
            for group, cams in self._camera_zone_groups.items():
                for cam in cams:
                    inverse[cam] = group
            self._camera_to_zone_group = inverse
        prompt = config.get("camera_announce_prompt")
        if isinstance(prompt, str) and prompt.strip():
            self._camera_announce_prompt = prompt
        else:
            self._camera_announce_prompt = _DEFAULT_CAMERA_ANNOUNCE_PROMPT
        per_label = config.get("camera_announce_per_label_prompts")
        if isinstance(per_label, dict):
            self._camera_announce_per_label_prompts = {
                str(k): str(v)
                for k, v in per_label.items()
                if isinstance(v, str) and v.strip()
            }
        if "enabled_context_providers" in config:
            raw = config["enabled_context_providers"]
            self._enabled_context_providers = list(raw) if raw is not None else None

    async def _greet_already_present(self) -> None:
        """Greet anyone already present at startup who hasn't been greeted today.

        Instead of greeting each person individually (which would cause
        announcements to step on each other), generates a single combined
        greeting for everyone present.

        Marks users as greeted BEFORE announcing so any concurrent
        ``presence.arrived`` event (which can fire seconds after the
        startup poll) sees them as already greeted and doesn't pile on.
        """
        if not self._in_greeting_window():
            logger.info("Startup greeting skipped — outside greeting window")
            return

        presence_svc = self._resolver.get_capability("presence") if self._resolver else None
        if not isinstance(presence_svc, PresenceProvider):
            logger.info("Startup greeting skipped — no presence service")
            return

        try:
            here = await presence_svc.who_is_here()
        except Exception:
            logger.warning("Startup greeting: could not check who is here", exc_info=True)
            return

        # Filter to people not yet greeted today
        to_greet_names: list[str] = []
        to_greet_ids: list[str] = []
        for p in here:
            if not await self._has_been_greeted_today(p.user_id):
                name = await self._get_display_name(p.user_id)
                to_greet_names.append(name)
                to_greet_ids.append(p.user_id)

        logger.info(
            "Startup greeting: %d present, %d to greet",
            len(here),
            len(to_greet_names),
        )

        if not to_greet_names:
            return

        # Mark as greeted FIRST — before AI generation and announce —
        # so concurrent _on_arrival handlers see the flag immediately.
        for uid in to_greet_ids:
            await self._mark_greeted(uid, "")

        # Collect recent greetings across all users for variety
        all_recent: list[str] = []
        for p in here:
            all_recent.extend(await self._get_recent_greetings(p.user_id))

        # Generate a single combined greeting.
        # Group greetings pass user_ids so single-person groups still
        # get per-user context; true multi-person groups skip per-user
        # context for simplicity in v1.
        greeting = await self._generate_group_greeting(
            to_greet_names, all_recent, user_ids=to_greet_ids
        )
        logger.info("Startup greeting: %s", greeting)

        await self._announce(greeting)

        # Update the greeting text now that we have it
        for uid in to_greet_ids:
            await self._mark_greeted(uid, greeting)

        if self._event_bus:
            await self._event_bus.publish(
                Event(
                    event_type="greeting.announced",
                    data={
                        "names": to_greet_names,
                        "greeting": greeting,
                        "startup": True,
                    },
                    source="greeting",
                )
            )

    async def _on_arrival(self, event: Event) -> None:
        """Handle a presence.arrived event."""
        user_id = event.data.get("user_id", "")
        if not user_id:
            return
        if not self._in_greeting_window():
            return
        await self._greet_user(user_id)

    async def _greet_user(self, user_id: str) -> None:
        """Greet a user if they haven't been greeted today.

        Serialized per-user so concurrent ``presence.arrived`` events
        for the same person can't race past the greeted-today check.
        """
        # Get or create per-user lock
        async with self._greeting_locks_guard:
            if user_id not in self._greeting_locks:
                self._greeting_locks[user_id] = asyncio.Lock()
            lock = self._greeting_locks[user_id]

        async with lock:
            if await self._has_been_greeted_today(user_id):
                return

            display_name = await self._get_display_name(user_id)
            recent = await self._get_recent_greetings(user_id)
            greeting = await self._generate_greeting(
                display_name, recent, user_id=user_id
            )

            logger.info("Greeting %s: %s", user_id, greeting)

            await self._mark_greeted(user_id, greeting)
            await self._announce(greeting)

            if self._event_bus:
                await self._event_bus.publish(
                    Event(
                        event_type="greeting.announced",
                        data={
                            "user_id": user_id,
                            "greeting": greeting,
                        },
                        source="greeting",
                    )
                )

    def _in_greeting_window(self) -> bool:
        """Check if current time is within the greeting window."""
        try:
            from zoneinfo import ZoneInfo

            now = datetime.now(ZoneInfo(self._timezone))
        except Exception:
            now = datetime.now(UTC)

        return self._start_hour <= now.hour < self._cutoff_hour

    async def _get_display_name(self, user_id: str) -> str:
        """Resolve a user_id to a display-friendly first name."""
        from gilbert.core.user_utils import resolve_display_name

        return await resolve_display_name(user_id, self._resolver, first_name_only=True)

    async def _has_been_greeted_today(self, user_id: str) -> bool:
        """Check if user has been greeted today."""
        if self._storage_backend is None:
            return False

        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        if not record:
            return False

        today = self._today_str()
        return bool(record.get("last_greeting_date") == today)

    async def _mark_greeted(self, user_id: str, greeting: str = "") -> None:
        """Mark user as greeted today and store the greeting text."""
        if self._storage_backend is None:
            return

        today = self._today_str()
        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        count = (record.get("greeting_count", 0) if record else 0) + 1

        # Keep a rolling log of recent greetings so the AI can avoid repeats
        recent: list[str] = record.get("recent_greetings", []) if record else []
        if greeting:
            recent.append(greeting)
            recent = recent[-10:]  # keep last 10

        await self._storage_backend.put(
            _GREETING_COLLECTION,
            user_id,
            {
                "user_id": user_id,
                "last_greeting_date": today,
                "greeting_count": count,
                "recent_greetings": recent,
            },
        )

    async def _get_recent_greetings(self, user_id: str) -> list[str]:
        """Get recent greeting texts for a user (for anti-repetition)."""
        if self._storage_backend is None:
            return []
        record = await self._storage_backend.get(_GREETING_COLLECTION, user_id)
        if not record:
            return []
        recent = record.get("recent_greetings", [])
        return list(recent) if isinstance(recent, list) else []

    def _today_str(self) -> str:
        """Get today's date string in the configured timezone."""
        try:
            from zoneinfo import ZoneInfo

            return datetime.now(ZoneInfo(self._timezone)).strftime("%Y-%m-%d")
        except Exception:
            return datetime.now(UTC).strftime("%Y-%m-%d")

    def _discover_context_providers(self) -> None:
        """Populate self._context_providers from the resolver.

        Idempotent: callable any time after self._resolver is set.
        """
        if self._resolver is None:
            self._context_providers = []
            return
        self._context_providers = [
            svc for svc in self._resolver.get_all("greeting_context")
            if isinstance(svc, GreetingContextProvider)
        ]

    def available_context_providers(self) -> list[dict[str, str]]:
        """Return the discovered providers' ids + labels for the settings
        UI. Order is stable (registration order)."""
        return [
            {"id": p.greeting_context_id, "label": p.greeting_context_label}
            for p in self._context_providers
        ]

    async def collect_context_block(self, user_id: str) -> str:
        """Call each enabled provider, format non-None results into a
        labeled block. Returns ``""`` when no providers contribute.

        A provider raising is logged and skipped — never blocks the
        greeting.
        """
        if not self._context_providers:
            return ""
        enabled = (
            set(self._enabled_context_providers)
            if self._enabled_context_providers is not None
            else None
        )
        entries: list[GreetingContext] = []
        for provider in self._context_providers:
            if enabled is not None and provider.greeting_context_id not in enabled:
                continue
            try:
                ctx = await provider.greeting_context(user_id)
            except Exception:
                logger.debug(
                    "GreetingContextProvider %s raised; skipping",
                    provider.greeting_context_id,
                    exc_info=True,
                )
                continue
            if ctx is None or not ctx.prose:
                continue
            entries.append(ctx)
        if not entries:
            return ""
        return "\n".join(f"{e.label}: {e.prose}" for e in entries)

    async def _generate_greeting(
        self,
        name: str,
        recent: list[str] | None = None,
        *,
        user_id: str | None = None,
    ) -> str:
        """Generate a personalized arrival greeting via AI, with fallback.

        ``user_id`` is required to fetch per-user context; when it's None
        the greeting still works, just without the contextual block.
        """
        if self._resolver is None:
            return f"Good morning, {name}!"
        ai_svc = self._resolver.get_capability("ai_chat")
        if not isinstance(ai_svc, AISamplingProvider):
            return f"Good morning, {name}!"

        style_instruction = f"\nStyle: {self._style}." if self._style else ""

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nHere are your recent greetings — do NOT repeat or closely "
                "paraphrase any of these. Be completely different in tone, "
                "structure, and word choice:\n" + "\n".join(f"- {g}" for g in recent[-7:])
            )

        context_section = ""
        if user_id:
            block = await self.collect_context_block(user_id)
            if block:
                context_section = (
                    "\n\nAvailable context (use what's relevant, skip what isn't):\n"
                    + block
                )

        prompt = self._arrival_greeting_prompt.format(
            name=name,
            style_instruction=style_instruction,
            avoid_section=avoid_section,
            context_section=context_section,
        )

        # tools_override=[] forces a zero-tool call regardless of the
        # profile's tool_mode, so the model can't accidentally call
        # `announce` (or anything else) as a side effect of generating
        # greeting text. Profile is still used for backend/model choice.
        try:
            response = await ai_svc.complete_one_shot(
                messages=[Message(role=MessageRole.USER, content=prompt)],
                profile_name=self._ai_profile,
                tools_override=[],
            )
            text = response.message.content.strip()
            if text and len(text) < 500:
                return text
        except Exception:
            logger.warning("AI greeting generation failed", exc_info=True)

        return f"Good morning, {name}!"

    async def _generate_group_greeting(
        self,
        names: list[str],
        recent: list[str] | None = None,
        user_ids: list[str] | None = None,
    ) -> str:
        """Generate a single greeting for multiple people."""
        if len(names) == 1:
            uid = user_ids[0] if user_ids else None
            return await self._generate_greeting(names[0], recent, user_id=uid)

        if self._resolver is None:
            return f"Good morning, {', '.join(names)}!"

        ai_svc = self._resolver.get_capability("ai_chat")
        if not isinstance(ai_svc, AISamplingProvider):
            return f"Good morning, {', '.join(names)}!"

        style_instruction = ""
        if self._style:
            style_instruction = f"\nStyle: {self._style}."

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nHere are recent greetings — do NOT repeat or closely "
                "paraphrase any of these. Be completely different:\n"
                + "\n".join(f"- {g}" for g in recent[-7:])
            )

        names_str = ", ".join(names[:-1]) + f", and {names[-1]}"
        prompt = (
            f"Generate a morning greeting for the crew: {names_str}. "
            f"You're Gilbert, an AI assistant at a business. Greet them as a group "
            f"with personality — vary your tone (witty, warm, dramatic, deadpan, etc.). "
            f"Mention a few names naturally. 2-3 sentences max. "
            f"Write ONLY the greeting."
            f"{style_instruction}{avoid_section}"
        )

        try:
            response = await ai_svc.complete_one_shot(
                messages=[Message(role=MessageRole.USER, content=prompt)],
                profile_name=self._ai_profile,
                tools_override=[],
            )
            text = response.message.content.strip()
            if text and len(text) < 500:
                return text
        except Exception:
            logger.warning("AI group greeting failed", exc_info=True)

        return f"Good morning, {names_str}!"

    async def _resolve_user_match(self, name: str) -> Any:
        """Delegate name → user lookup to the user service.

        Returns the ``NameMatch`` (with ``user_id`` + ``confidence``)
        or ``None`` when the resolver isn't wired, the user service
        isn't around, or the lookup didn't find a unique match.
        """
        if not name or self._resolver is None:
            return None
        users_svc = self._resolver.get_capability("users")
        if not isinstance(users_svc, UserManagementProvider):
            return None
        try:
            return await users_svc.resolve_user_id_by_name(name)
        except Exception:
            logger.debug("greet: resolve_user_id_by_name failed", exc_info=True)
            return None

    async def _generate_greeting_enhanced(
        self, name: str, recent: list[str] | None = None
    ) -> str:
        """Generate a personalized greeting with full tool access.

        Unlike ``_generate_greeting`` (used by the automatic arrival
        paths, which forces ``tools_override=[]`` so the model can't
        accidentally call ``announce`` while generating greeting text),
        this path runs ``ai_svc.chat()`` against the configured
        ``ai_profile`` with its tools intact. That lets the model
        consult whatever data-lookup tools the profile exposes —
        recent activity, time logs, presence, project status, etc. —
        before writing the greeting.

        The prompt template is the configurable
        ``greeting.enhanced_greeting_prompt`` setting (falls back to
        the bundled default if the user clears it or formatting fails);
        a soft prompt-level guardrail asks the model to stick to
        read-only data-lookup tools. On any failure we fall back to a
        plain ``"Good morning, <name>!"``.
        """
        if self._resolver is None:
            return f"Good morning, {name}!"
        ai_svc = self._resolver.get_capability("ai_chat")
        if not isinstance(ai_svc, AIProvider):
            return f"Good morning, {name}!"

        style_instruction = ""
        if self._style:
            style_instruction = f"\nStyle: {self._style}."

        avoid_section = ""
        if recent:
            avoid_section = (
                "\n\nRecent greetings — do NOT repeat or closely paraphrase any "
                "of these. Be completely different in tone, structure, and word "
                "choice:\n" + "\n".join(f"- {g}" for g in recent[-7:])
            )

        subs = {
            "name": name,
            "style_instruction": style_instruction,
            "avoid_section": avoid_section,
        }
        try:
            prompt = self._enhanced_greeting_prompt.format_map(subs)
        except (KeyError, IndexError, ValueError):
            # User-edited template had a bad placeholder — fall back to
            # the bundled default so /greet keeps working until they fix
            # the saved value.
            logger.warning(
                "Enhanced greeting prompt failed to format; falling back to default",
                exc_info=True,
            )
            prompt = _DEFAULT_ENHANCED_GREETING_PROMPT.format_map(subs)

        try:
            result = await ai_svc.chat(
                user_message=prompt,
                user_ctx=UserContext.SYSTEM,
                ai_call="greeting",
                ai_profile=self._ai_profile,
            )
            text = (result.response_text or "").strip()
            if text and len(text) < 500:
                return text
        except Exception:
            logger.warning("Enhanced AI greeting generation failed", exc_info=True)

        return f"Good morning, {name}!"

    # ── ToolProvider Protocol ───────────────────────────────────

    @property
    def tool_provider_name(self) -> str:
        return "greeting"

    def get_tools(self, user_ctx: UserContext | None = None) -> list[ToolDefinition]:
        if not self._enabled:
            return []
        return [
            ToolDefinition(
                name="greet",
                slash_command="greet",
                slash_help="Announce a personalized greeting: /greet <name>",
                description=(
                    "Generate and announce a personalized greeting for someone. "
                    "Use this when a user asks you to greet someone or welcome them."
                ),
                parameters=[
                    ToolParameter(
                        name="name",
                        type=ToolParameterType.STRING,
                        description="Name of the person to greet.",
                    ),
                ],
                required_role="user",
            ),
            ToolDefinition(
                name="mute_camera_alerts",
                slash_command="mute",
                slash_group="cameras",
                slash_help=(
                    "/cameras mute [camera] [label] [until] — silence "
                    "camera-event announcements; bus events still flow"
                ),
                description=(
                    "Silence the announcement for camera detection "
                    "events without muting the bus event itself. "
                    "``camera=None`` mutes the label across all "
                    "cameras; ``label=None`` mutes every label for "
                    "the camera. ``until`` accepts the same time-"
                    "window grammar as latest_clips (e.g. ``8h``, "
                    "``today``, ISO 8601). The first call returns a "
                    "Confirm/Cancel UI block; the AI re-invokes with "
                    "``confirm=true`` after the user clicks Confirm."
                ),
                parameters=[
                    ToolParameter(
                        name="camera",
                        type=ToolParameterType.STRING,
                        description="Camera to mute (or empty for all).",
                        required=False,
                    ),
                    ToolParameter(
                        name="label",
                        type=ToolParameterType.STRING,
                        description="Label to mute (or empty for all).",
                        required=False,
                    ),
                    ToolParameter(
                        name="until",
                        type=ToolParameterType.STRING,
                        description=(
                            "When the mute expires. Same grammar as "
                            "latest_clips. Default: until 08:00 "
                            "tomorrow local."
                        ),
                        required=False,
                    ),
                    ToolParameter(
                        name="confirm",
                        type=ToolParameterType.BOOLEAN,
                        description=(
                            "Set true on the second call after the "
                            "user clicks Confirm in the UI block."
                        ),
                        required=False,
                        default=False,
                    ),
                ],
                required_role="user",
            ),
        ]

    async def execute_tool(
        self, name: str, arguments: dict[str, Any]
    ) -> Any:
        if name == "greet":
            person_name = str(arguments.get("name", "")).strip()
            if not person_name:
                return "I need a name to greet."

            # Resolve the input to a user_id when we can. Below the
            # confidence threshold we still greet by raw name, but do
            # not read or write user-keyed greeting history.
            match = await self._resolve_user_match(person_name)
            user_id: str | None = None
            display_name = person_name
            if (
                match is not None
                and match.confidence >= _GREETING_MATCH_CONFIDENCE_THRESHOLD
            ):
                user_id = match.user_id
                display_name = await self._get_display_name(user_id)

            recent = await self._get_recent_greetings(user_id) if user_id else []
            greeting = await self._generate_greeting_enhanced(display_name, recent)

            if user_id:
                await self._mark_greeted(user_id, greeting)

            await self._announce(greeting)
            return f'Greeted {display_name}: "{greeting}"'
        if name == "mute_camera_alerts":
            return await self._tool_mute_camera_alerts(arguments)
        raise KeyError(f"Unknown tool: {name}")

    # ── WS Handler Protocol ─────────────────────────────────────────

    def get_ws_handlers(self) -> dict[str, Any]:
        """Return the frame-type → handler map for this service.

        Implements ``WsHandlerProvider`` (structurally — the protocol is
        runtime-checkable, so explicit inheritance isn't required).
        """
        return {
            "greeting.context_providers.list": self._ws_list_context_providers,
        }

    async def _ws_list_context_providers(
        self, conn: Any, frame: dict[str, Any]
    ) -> dict[str, Any]:
        """List discovered greeting-context providers and whether each is
        currently included in arrival greetings.

        Returns ``{providers: [{id, label, enabled}, ...]}``.
        """
        enabled_set = (
            set(self._enabled_context_providers)
            if self._enabled_context_providers is not None
            else None  # None = all enabled
        )
        return {
            "providers": [
                {
                    "id": p.greeting_context_id,
                    "label": p.greeting_context_label,
                    "enabled": enabled_set is None or p.greeting_context_id in enabled_set,
                }
                for p in self._context_providers
            ],
        }

    async def _tool_mute_camera_alerts(
        self,
        arguments: dict[str, Any],
    ) -> Any:
        from gilbert.core.services._ui_blocks import confirm_or_execute

        camera = (arguments.get("camera") or "").strip()
        label = (arguments.get("label") or "").strip()
        until_raw = arguments.get("until") or ""

        until_ms = _parse_until_arg(until_raw, self._timezone)

        async def _do_mute() -> str:
            if self._storage_backend is None:
                return "Storage unavailable; cannot persist mute."
            entity_id = f"{camera or '*'}.{label or '*'}"
            await self._storage_backend.put(
                _CAMERA_MUTES_COLLECTION,
                entity_id,
                {
                    "camera": camera,
                    "label": label,
                    "until_ms": until_ms,
                    "set_at_ms": int(datetime.now(UTC).timestamp() * 1000),
                },
            )
            until_iso = (
                datetime.fromtimestamp(until_ms / 1000.0, tz=UTC).isoformat()
                if until_ms
                else "no end"
            )
            return (
                f"Muted {camera or 'all'} / "
                f"{label or 'all'} until {until_iso}."
            )

        until_iso = (
            datetime.fromtimestamp(until_ms / 1000.0, tz=UTC).isoformat()
            if until_ms
            else "no end"
        )
        target = (
            f"{camera or '*all cameras*'} / "
            f"{label or '*all labels*'}"
        )
        return await confirm_or_execute(
            confirm=bool(arguments.get("confirm")),
            tool_name="mute_camera_alerts",
            title="Mute camera alerts",
            summary=(
                f"Mute {target} until {until_iso}? Bus events still "
                f"flow; only the announcement is suppressed."
            ),
            summary_lines=[
                f"camera: {camera or 'all'}",
                f"label: {label or 'all'}",
                f"until: {until_iso}",
            ],
            arguments={
                "camera": camera,
                "label": label,
                "until": until_raw,
            },
            execute=_do_mute,
        )

    # ── Camera-event announce + dedup ──────────────────────────────

    async def _on_camera_event(self, event: Event) -> None:
        """React to ``camera.event.detected`` — announce when configured."""
        if not self._announce_camera_labels:
            return
        data = event.data or {}
        label = str(data.get("label") or "")
        camera = str(data.get("camera") or "")
        if not label or not camera:
            return
        if label not in self._announce_camera_labels:
            return

        # Mute check — drop the announce but the bus event still flows.
        if await self._is_camera_muted(camera, label):
            logger.debug(
                "camera-event announce suppressed (muted): %s/%s",
                camera,
                label,
            )
            return

        # Per-label dedup key shape (default: package=label, person=label+zone_group).
        key_parts = self._camera_announce_dedup_keys.get(label, ["label", "camera"])
        zone_group = self._camera_to_zone_group.get(camera, camera)
        rendered: list[str] = []
        for part in key_parts:
            if part == "label":
                rendered.append(label)
            elif part == "camera":
                rendered.append(camera)
            elif part == "zone_group":
                rendered.append(zone_group)
        dedup_key = "|".join(rendered)

        now = datetime.now(UTC).timestamp()
        last = self._camera_announce_dedup_state.get(dedup_key, 0.0)
        if now - last < self._camera_announce_dedup_seconds:
            return
        self._camera_announce_dedup_state[dedup_key] = now

        # Generate the alert sentence.
        sentence = await self._generate_camera_alert(label, camera)
        await self._announce(sentence)

    async def _is_camera_muted(self, camera: str, label: str) -> bool:
        if self._storage_backend is None:
            return False
        now_ms = int(datetime.now(UTC).timestamp() * 1000)
        for entity_id in (
            f"{camera}.{label}",
            f"{camera}.*",
            f"*.{label}",
            "*.*",
        ):
            row = await self._storage_backend.get(
                _CAMERA_MUTES_COLLECTION, entity_id
            )
            if row is None:
                continue
            until = int(row.get("until_ms") or 0)
            if until == 0 or until > now_ms:
                return True
        return False

    async def _generate_camera_alert(self, label: str, camera: str) -> str:
        # Time-of-day bucket
        try:
            from zoneinfo import ZoneInfo

            now = datetime.now(ZoneInfo(self._timezone))
        except Exception:
            now = datetime.now(UTC)
        hour = now.hour
        if hour < 5:
            time_of_day = "late_night"
        elif hour < 11:
            time_of_day = "morning"
        elif hour < 17:
            time_of_day = "midday"
        else:
            time_of_day = "evening"

        prompt_template = self._camera_announce_per_label_prompts.get(
            label, self._camera_announce_prompt
        )
        try:
            prompt = prompt_template.format(
                label=label, camera=camera, time_of_day=time_of_day
            )
        except (KeyError, IndexError, ValueError):
            prompt = (
                f"Brief alert: {label} at the {camera} camera "
                f"({time_of_day})."
            )

        if self._resolver is None:
            return f"{label.capitalize()} at the {camera}."
        ai_svc = self._resolver.get_capability("ai_chat")
        if not isinstance(ai_svc, AISamplingProvider):
            return f"{label.capitalize()} at the {camera}."
        try:
            response = await ai_svc.complete_one_shot(
                messages=[Message(role=MessageRole.USER, content=prompt)],
                profile_name=self._ai_profile,
                tools_override=[],
            )
            text = response.message.content.strip()
            if text and len(text) < 200:
                return text
        except Exception:
            logger.warning("Camera alert generation failed", exc_info=True)
        return f"{label.capitalize()} at the {camera}."

    # ── Announce ────────────────────────────────────────────────

    async def _announce(self, text: str) -> None:
        """Announce greeting via speakers."""
        if self._resolver is None:
            return

        speaker_svc = self._resolver.get_capability("speaker_control")
        if not isinstance(speaker_svc, SpeakerProvider):
            logger.debug("No speaker service — greeting not announced: %s", text)
            return

        try:
            await speaker_svc.announce(
                text,
                speaker_names=self._speakers or None,
                context="Cheery welcome greeting for someone arriving at the shop",
            )
        except Exception:
            logger.warning("Failed to announce greeting", exc_info=True)

def _parse_until_arg(value: str, tz_name: str) -> int:
    """Parse a mute ``until`` argument into epoch ms.

    Empty / unset → "until 08:00 tomorrow local" per the spec.
    Accepts the camera tool grammar: ``{N}m`` / ``{N}h`` / ``{N}d``
    (relative), ``today`` / ``tomorrow`` (start-of-day), or ISO 8601.
    """
    import re as _re
    from datetime import UTC, datetime, time, timedelta
    from zoneinfo import ZoneInfo

    try:
        tz = ZoneInfo(tz_name) if tz_name else UTC
    except Exception:
        tz = UTC

    if not value:
        # Default: 08:00 tomorrow local.
        now_local = datetime.now(tz)
        tomorrow = now_local.date() + timedelta(days=1)
        until_local = datetime.combine(tomorrow, time(8, 0), tzinfo=tz)
        return int(until_local.timestamp() * 1000)

    v = value.strip().lower()
    match = _re.fullmatch(r"(\d+)([mhd])", v)
    if match:
        count, unit = int(match.group(1)), match.group(2)
        seconds = {"m": 60, "h": 3600, "d": 86400}[unit]
        return int(
            (datetime.now(UTC) + timedelta(seconds=count * seconds)).timestamp()
            * 1000
        )

    if v == "today":
        now_local = datetime.now(tz)
        end = datetime.combine(now_local.date(), time(23, 59, 59), tzinfo=tz)
        return int(end.timestamp() * 1000)
    if v == "tomorrow":
        now_local = datetime.now(tz)
        tomorrow = now_local.date() + timedelta(days=1)
        end = datetime.combine(tomorrow, time(8, 0), tzinfo=tz)
        return int(end.timestamp() * 1000)

    try:
        normalized = value.replace("Z", "+00:00")
        dt = datetime.fromisoformat(normalized)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=tz)
        return int(dt.timestamp() * 1000)
    except ValueError:
        # Fall back to default
        return _parse_until_arg("", tz_name)
